# See https://www.fastruby.io/blog/ruby/code-quality/how-we-use-rubocop-and-standardrb.html
require:
  - rubocop-minitest
  - rubocop-rails
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - bin/*
    - config/puma.rb

Layout/ExtraSpacing:
  Exclude:
    - config/environments/*

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - config/environments/*

Rails/CreateTableWithTimestamps:
  Exclude:
    - db/migrate/*_create_email_verification_tokens.rb
    - db/migrate/*_create_password_reset_tokens.rb

# Rails/I18nLocaleTexts may be enabled in future but
# for now it is disabled to make RuboCop not so noisy.
Rails/I18nLocaleTexts:
  Enabled: false

Style/GlobalStdStream:
  Exclude:
    - config/environments/production.rb

Minitest:
  Enabled: true
Rails:
  Enabled: true
