# See https://www.fastruby.io/blog/ruby/code-quality/how-we-use-rubocop-and-standardrb.html
require:
  - rubocop-minitest
  - rubocop-rails
  - standard

inherit_gem:
  standard: config/base.yml

Minitest:
  Enabled: true
Rails:
  Enabled: true
