# See https://www.fastruby.io/blog/ruby/code-quality/how-we-use-rubocop-and-standardrb.html
require:
  - rubocop-minitest
  - rubocop-rails
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - config/puma.rb

Layout/ExtraSpacing:
  Exclude:
    - config/environments/*

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - config/environments/*

Style/GlobalStdStream:
  Exclude:
    - config/environments/production.rb

Minitest:
  Enabled: true
Rails:
  Enabled: true
