require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'node_modules/node-sass/src/libsass/contrib/libsass.spec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Capybara/FeatureMethods:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/ExampleLength:
  Max: 10

RSpec/ImplicitExpect:
  # We want to write "should" when using shoulda matchers
  Enabled: false
