require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/node-sass/src/**/*'
    - 'script/**/*'
    - 'tmp/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Capybara/FeatureMethods:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/ExampleLength:
  Max: 10

RSpec/ImplicitExpect:
  # We want to write "should" when using shoulda matchers
  Enabled: false
