require: rubocop-rspec

Capybara/FeatureMethods:
  Enabled: false

Layout/AlignHash:
  EnforcedColonStyle: table

RSpec/ExampleLength:
  Max: 10

RSpec/ImplicitExpect:
  # We want to write "should" when using shoulda matchers
  Enabled: false
