extend_config:
  - .standard_extensions.yml

ignore:
  - config/environments/*:
      - Layout/ExtraSpacing
      - Layout/SpaceInsideArrayLiteralBrackets
  - config/environments/production.rb:
      - Style/GlobalStdStream
  - config/puma.rb
  - db/migrate/*_create_email_verification_tokens.rb:
      - Rails/CreateTableWithTimestamps
  - db/migrate/*_create_password_reset_tokens.rb:
      - Rails/CreateTableWithTimestamps
