# First try
POST http://asgard:3000/api/v01/brainz_releases
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "brainz_release",
    "attributes": {
      "offered": "8866e226-7cd6-414e-b7d2-6ae0b0df6715"
    }
  }
}