version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # The following line about volumes was taken from
    # https://docs.docker.com/compose/rails/
    # It causes errors because it sets some paths under tmp/
    # to the root owner. Therefore it was commented out.
    # volumes:
    #   - .:/var/www/kleinodien
    ports:
      - "3000:3000"
    depends_on:
      - db
