version: '2'
services:
  db:
    image: postgres
    volumes:
      - kleinodien_postgresql_data:/var/lib/postgresql/data
    
  app:
    build: .
    environment:
      RAILS_ENV: $RAILS_ENV

    links:
      - db
    expose:
      - "3000"
    depends_on:
      - db

  fetcher:
    build: .
    depends_on:
      - app
    entrypoint: bin/fetcher.rb

  web:
    build:
      context: .
      dockerfile: config/containers/Dockerfile-nginx
    links:
      - app
    ports:
      - "8888:80"

volumes:
  kleinodien_postgresql_data: {}
