version: '2'
services:
  db:
    image: "postgres:13.0"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.5-alpine
    expose:
      - "6379"

  app:
    build: .
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_ENV=$RAILS_ENV

    expose:
      - "3000"
    depends_on:
      - db
      - redis

  cover_art_import_worker:
    build: .
    depends_on:
      - db
      - redis
    entrypoint: config/containers/import_worker/entrypoint.sh
    environment:
      - IMPORT_QUEUE_NAME=coverart
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

  brainz_import_worker:
    build: .
    depends_on:
      - db
      - redis
    entrypoint: config/containers/import_worker/entrypoint.sh
    environment:
      - IMPORT_QUEUE_NAME=brainz
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

  web:
    build:
      context: .
      dockerfile: config/containers/nginx/Dockerfile
    links:
      - app
    ports:
      - "8888:80"

volumes:
  postgresql_data: {}
