 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/import_orders", type: :request do
  # ImportOrder. As you add validations to ImportOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ImportOrder.create! valid_attributes
      get import_orders_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      import_order = ImportOrder.create! valid_attributes
      get import_order_url(import_order)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_import_order_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      import_order = ImportOrder.create! valid_attributes
      get edit_import_order_url(import_order)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ImportOrder" do
        expect {
          post import_orders_url, params: { import_order: valid_attributes }
        }.to change(ImportOrder, :count).by(1)
      end

      it "redirects to the created import_order" do
        post import_orders_url, params: { import_order: valid_attributes }
        expect(response).to redirect_to(import_order_url(ImportOrder.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ImportOrder" do
        expect {
          post import_orders_url, params: { import_order: invalid_attributes }
        }.to change(ImportOrder, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post import_orders_url, params: { import_order: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested import_order" do
        import_order = ImportOrder.create! valid_attributes
        patch import_order_url(import_order), params: { import_order: new_attributes }
        import_order.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the import_order" do
        import_order = ImportOrder.create! valid_attributes
        patch import_order_url(import_order), params: { import_order: new_attributes }
        import_order.reload
        expect(response).to redirect_to(import_order_url(import_order))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        import_order = ImportOrder.create! valid_attributes
        patch import_order_url(import_order), params: { import_order: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested import_order" do
      import_order = ImportOrder.create! valid_attributes
      expect {
        delete import_order_url(import_order)
      }.to change(ImportOrder, :count).by(-1)
    end

    it "redirects to the import_orders list" do
      import_order = ImportOrder.create! valid_attributes
      delete import_order_url(import_order)
      expect(response).to redirect_to(import_orders_url)
    end
  end
end
