 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/release_heads", type: :request do
  # ReleaseHead. As you add validations to ReleaseHead, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ReleaseHead.create! valid_attributes
      get release_heads_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      release_head = ReleaseHead.create! valid_attributes
      get release_head_url(release_head)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_release_head_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      release_head = ReleaseHead.create! valid_attributes
      get edit_release_head_url(release_head)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ReleaseHead" do
        expect {
          post release_heads_url, params: { release_head: valid_attributes }
        }.to change(ReleaseHead, :count).by(1)
      end

      it "redirects to the created release_head" do
        post release_heads_url, params: { release_head: valid_attributes }
        expect(response).to redirect_to(release_head_url(ReleaseHead.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ReleaseHead" do
        expect {
          post release_heads_url, params: { release_head: invalid_attributes }
        }.to change(ReleaseHead, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post release_heads_url, params: { release_head: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested release_head" do
        release_head = ReleaseHead.create! valid_attributes
        patch release_head_url(release_head), params: { release_head: new_attributes }
        release_head.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the release_head" do
        release_head = ReleaseHead.create! valid_attributes
        patch release_head_url(release_head), params: { release_head: new_attributes }
        release_head.reload
        expect(response).to redirect_to(release_head_url(release_head))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        release_head = ReleaseHead.create! valid_attributes
        patch release_head_url(release_head), params: { release_head: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested release_head" do
      release_head = ReleaseHead.create! valid_attributes
      expect {
        delete release_head_url(release_head)
      }.to change(ReleaseHead, :count).by(-1)
    end

    it "redirects to the release_heads list" do
      release_head = ReleaseHead.create! valid_attributes
      delete release_head_url(release_head)
      expect(response).to redirect_to(release_heads_url)
    end
  end
end
