 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/release_copies", type: :request do
  # ReleaseCopy. As you add validations to ReleaseCopy, be sure to
  # adjust the attributes here as well.
  let(:user) { FactoryBot.create(:user) }

  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  before { sign_in user }

  describe "GET /index" do
    it "renders a successful response" do
      ReleaseCopy.create! valid_attributes
      get release_copies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      release_copy = ReleaseCopy.create! valid_attributes
      get release_copy_url(release_copy)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_release_copy_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      release_copy = ReleaseCopy.create! valid_attributes
      get edit_release_copy_url(release_copy)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ReleaseCopy" do
        expect {
          post release_copies_url, params: { release_copy: valid_attributes }
        }.to change(ReleaseCopy, :count).by(1)
      end

      it "redirects to the created release_copy" do
        post release_copies_url, params: { release_copy: valid_attributes }
        expect(response).to redirect_to(release_copy_url(ReleaseCopy.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ReleaseCopy" do
        expect {
          post release_copies_url, params: { release_copy: invalid_attributes }
        }.to change(ReleaseCopy, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post release_copies_url, params: { release_copy: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested release_copy" do
        release_copy = ReleaseCopy.create! valid_attributes
        patch release_copy_url(release_copy), params: { release_copy: new_attributes }
        release_copy.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the release_copy" do
        release_copy = ReleaseCopy.create! valid_attributes
        patch release_copy_url(release_copy), params: { release_copy: new_attributes }
        release_copy.reload
        expect(response).to redirect_to(release_copy_url(release_copy))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        release_copy = ReleaseCopy.create! valid_attributes
        patch release_copy_url(release_copy), params: { release_copy: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested release_copy" do
      release_copy = ReleaseCopy.create! valid_attributes
      expect {
        delete release_copy_url(release_copy)
      }.to change(ReleaseCopy, :count).by(-1)
    end

    it "redirects to the release_copies list" do
      release_copy = ReleaseCopy.create! valid_attributes
      delete release_copy_url(release_copy)
      expect(response).to redirect_to(release_copies_url)
    end
  end
end
