 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/release_images", type: :request do
  # ReleaseImage. As you add validations to ReleaseImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ReleaseImage.create! valid_attributes
      get release_images_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      release_image = ReleaseImage.create! valid_attributes
      get release_image_url(release_image)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_release_image_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      release_image = ReleaseImage.create! valid_attributes
      get edit_release_image_url(release_image)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ReleaseImage" do
        expect {
          post release_images_url, params: { release_image: valid_attributes }
        }.to change(ReleaseImage, :count).by(1)
      end

      it "redirects to the created release_image" do
        post release_images_url, params: { release_image: valid_attributes }
        expect(response).to redirect_to(release_image_url(ReleaseImage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ReleaseImage" do
        expect {
          post release_images_url, params: { release_image: invalid_attributes }
        }.to change(ReleaseImage, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post release_images_url, params: { release_image: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested release_image" do
        release_image = ReleaseImage.create! valid_attributes
        patch release_image_url(release_image), params: { release_image: new_attributes }
        release_image.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the release_image" do
        release_image = ReleaseImage.create! valid_attributes
        patch release_image_url(release_image), params: { release_image: new_attributes }
        release_image.reload
        expect(response).to redirect_to(release_image_url(release_image))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        release_image = ReleaseImage.create! valid_attributes
        patch release_image_url(release_image), params: { release_image: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested release_image" do
      release_image = ReleaseImage.create! valid_attributes
      expect {
        delete release_image_url(release_image)
      }.to change(ReleaseImage, :count).by(-1)
    end

    it "redirects to the release_images list" do
      release_image = ReleaseImage.create! valid_attributes
      delete release_image_url(release_image)
      expect(response).to redirect_to(release_images_url)
    end
  end
end
