# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fde45d154fe7cb4b488e8b48452bc6ed8ca95fdc51e55bb3b7c760fcddc09984c8749e37bf973c09a57a1cfee42d7fedd0f331031ceb3a3d3dde571f00b3dc2

test:
  secret_key_base: 1d7cf684f3768fa2c61324b7203dea4293ace7d649cb2ff0405afa9a189f86e7ee8cbeb07c05bcd4ae6d84b26177db1a4647f58a67073de110062d592f65582c

kocli:
  secret_key_base: '86a7172cc601016fd643efc35a4a91ee6dd29072b9c147693e042528c01ab31ffabcae8c0fd278fa2abe49bb09a3b5527b82fe8365ae8aab1c4663
f3d84ad807'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
