# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3c8e857b793536cb8a2e1f80e2b8e83f3f8613c99f1d2f2f65a540f83d39444ea4979e63ddcb4df19b2d27bcf5cd7a4f127c8b931e259a54b7a4f5023241cac

test:
  secret_key_base: 18ea9ac2f502feb6536ef814be15790730a1d90fb63c0026121eb0322f5135a1e11a9946752f108c94f91656ef12c50ae160383c613b75817d1e87e426f5fb09

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
