# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b1c5c466404f1f83a9ea7bb898161a881b7bb3fdf6b8617f875365a8d86b13d4218e1fdb852b1c98ddd3d68e63f49ce7175a6aa1f68f26d9cb9a8bb226e4883e

test:
  secret_key_base: 566ecf6ff11d340f9820f7509833ba0e11e13b2693abc84213d85b7b19b49e21bcb9336bc74416b9854cc76df45ac77e1bcb501f0705e062de020d8df00a535d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
